# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Database-Wrapper
version:      1.04
version_from: lib/Database/Wrapper.pm
installdirs:  site
requires:
    DBI:                           1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
